-- Create Tables

CREATE TABLE CIDADE(
	COD_CIDADE INT NOT NULL,
	NOME_CIDADE VARCHAR(30) NOT NULL,
	FUNDACAO DATE
);

CREATE TABLE ALUNOS(
	MATRICULA INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
);

CREATE TABLE PROFESSORES(
	MATRICULA INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	FORMACAO VARCHAR(100) NOT NULL,
);

CREATE TABLE DISCIPLINAS(
	CODIGO_DISCIPLINA INT NOT NULL,
	NOME_DISCIPLINA VARCHAR(100) NOT NULL,
	CARGA_HORARIA NUMERIC(3),
	EMENTA VARCHAR(4000) NOT NULL,
	CODIGO_DISCIPLINA_DEPENDENCIA INT,
);

CREATE TABLE OFERTAS(
	CODIGO_OFERTA INT NOT NULL,
	HORARIO_INICIAL DATETIME NOT NULL,
	HORARIO_FINAL DATETIME NOT NULL,
	MATRICULA NUMERIC(5) NOT NULL,
	CODIGO_DISCIPLINA NUMERIC NOT NULL,
);

CREATE TABLE ALUNOS_OFERTAS(
	MATRICULA NUMERIC NOT NULL,
	CODIGO_OFERTA NUMERIC NOT NULL,
	LIMITE_ALUNIOS NUMERIC NOT NULL,
	SEMESTRE VARCHAR(6) NOT NULL,
	DATA_INICIAL DATE NOT NULL,
	DATA_FINAL DATE NOT NULL, --TIME IS NOT NECESSARY
);

CREATE TABLE TELEFONES(
	TELEFONE VARCHAR(11) NOT NULL,
	MATRICULA NUMERIC NOT NULL,
);

-- Count the Tuples (Rows) of a Table
SELECT count(*) FROM ALUNOS;
SELECT count(1) FROM PROFESSORES;
SELECT count(*) FROM OFERTAS;
SELECT count(*) FROM ALUNOS_OFERTAS;
SELECT count(1) FROM DISCIPLINAS;
SELECT count(*) FROM TELEFONES;

-- Drop Tables
DROP TABLE ALUNOS;
DROP TABLE PROFESSORES;
DROP TABLE OFERTAS;
DROP TABLE ALUNOS_OFERTAS;
DROP TABLE DISCIPLINAS;
DROP TABLE TELEFONES;


-- Inserting Data
INSERT INTO PROFESSORES (MATRICULA, NOME, FORMACAO)
VALUES (1, 'Davi Rodrigues', 'Mestrado');


-- Selecting
SELECT * FROM PROFESSORES;
SELECT * FROM ALUNOS;
SELECT * FROM OFERTAS;
SELECT * FROM DISCIPLINAS;
SELECT * FROM TELEFONES;
SELECT * FROM ALUNOS_OFERTAS;


-- Creating Views
CREATE VIEW vwProfessores AS
SELECT MATRICULA AS COD,
	   NOME AS NOME,
	   FORMACAO AS TITULO
FROM PROFESSORES


-- Alter Views
ALTER VIEW vwProfessores AS
SELECT MATRICULA AS CODIGO,
       NOME AS NOME_COMPLETO,
	   FORMACAO AS TITULO
FROM PROFESSORES
WHERE NOME LIKE 'D%'


-- Droping View
DROP VIEW vwProfessores;


SELECT * FROM vwProfessores;


-- Alter Table Section


-- Alter Table and Add Column
ALTER TABLE PROFESSORES 
	ADD EMAIL VARCHAR(255) UNIQUE,
	ADMISSION_DATE DATE;

-- Insert into a specific lineXcolumn
UPDATE PROFESSORES
SET EMAIL = 'davirnascimentox@gmail.com',
	ADMISSION_DATE = '2024-10-10'
WHERE MATRICULA = 1;


-- Alter Column Name . Is necessary to use the sp_rename stored procedure instead of ALTER TABLE <TABLE_NAME> RENAME ...
EXEC sp_rename 'PROFESSORES.MATRICULA', 'ID', 'COLUMN';


-- Alter Table Name
EXEC sp_rename 'TEACHERS', 'PROFESSORES';



-- Transaction
BEGIN TRANSACTION

ALTER TABLE PROFESSORES
DROP COLUMN ADMISSION_DATE;

ROLLBACK TRANSACTION


-- Add Primary Key
ALTER TABLE PROFESSORES
ADD CONSTRAINT PK_PROFESSORES PRIMARY KEY (ID);

-- add a constraint
ALTER TABLE PROFESSORES
ADD CONSTRAINT EMAIL UNIQUE (EMAIL);

SELECT * FROM PROFESSORES
INSERT INTO PROFESSORES (ID, NOME, FORMACAO, EMAIL, ADMISSION_DATE)
VALUES (2, 'Andressa Silva', 'Doutorado', 'andressasilvamendes@gmail.com', '2024-10-10')


-- Drop